/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnggotaRouteImport } from './routes/anggota'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as ProdukRouteImport } from './routes/produk'
import { Route as PulihkanRouteImport } from './routes/pulihkan'
import { Route as RingkasanRouteImport } from './routes/ringkasan'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as RiwayatIndexRouteImport } from './routes/riwayat.index'
import { Route as RiwayatOrderIdRouteImport } from './routes/riwayat.$orderId'
import { Route as SuksesOrderIdRouteImport } from './routes/sukses.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaRoute = AnggotaRouteImport.update({
  id: '/anggota',
  path: '/anggota',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukRoute = ProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => rootRouteImport,
} as any)
const PulihkanRoute = PulihkanRouteImport.update({
  id: '/pulihkan',
  path: '/pulihkan',
  getParentRoute: () => rootRouteImport,
} as any)
const RingkasanRoute = RingkasanRouteImport.update({
  id: '/ringkasan',
  path: '/ringkasan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const RiwayatIndexRoute = RiwayatIndexRouteImport.update({
  id: '/riwayat/',
  path: '/riwayat/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiwayatOrderIdRoute = RiwayatOrderIdRouteImport.update({
  id: '/riwayat/$orderId',
  path: '/riwayat/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const SuksesOrderIdRoute = SuksesOrderIdRouteImport.update({
  id: '/sukses/$orderId',
  path: '/sukses/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anggota': typeof AnggotaRoute
  '/checkout': typeof CheckoutRoute
  '/keranjang': typeof KeranjangRoute
  '/laporan': typeof LaporanRoute
  '/masuk': typeof MasukRoute
  '/produk': typeof ProdukRoute
  '/pulihkan': typeof PulihkanRoute
  '/ringkasan': typeof RingkasanRoute
  '/api/health': typeof ApiHealthRoute
  '/riwayat/$orderId': typeof RiwayatOrderIdRoute
  '/sukses/$orderId': typeof SuksesOrderIdRoute
  '/riwayat/': typeof RiwayatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anggota': typeof AnggotaRoute
  '/checkout': typeof CheckoutRoute
  '/keranjang': typeof KeranjangRoute
  '/laporan': typeof LaporanRoute
  '/masuk': typeof MasukRoute
  '/produk': typeof ProdukRoute
  '/pulihkan': typeof PulihkanRoute
  '/ringkasan': typeof RingkasanRoute
  '/api/health': typeof ApiHealthRoute
  '/riwayat/$orderId': typeof RiwayatOrderIdRoute
  '/sukses/$orderId': typeof SuksesOrderIdRoute
  '/riwayat': typeof RiwayatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anggota': typeof AnggotaRoute
  '/checkout': typeof CheckoutRoute
  '/keranjang': typeof KeranjangRoute
  '/laporan': typeof LaporanRoute
  '/masuk': typeof MasukRoute
  '/produk': typeof ProdukRoute
  '/pulihkan': typeof PulihkanRoute
  '/ringkasan': typeof RingkasanRoute
  '/api/health': typeof ApiHealthRoute
  '/riwayat/$orderId': typeof RiwayatOrderIdRoute
  '/sukses/$orderId': typeof SuksesOrderIdRoute
  '/riwayat/': typeof RiwayatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anggota'
    | '/checkout'
    | '/keranjang'
    | '/laporan'
    | '/masuk'
    | '/produk'
    | '/pulihkan'
    | '/ringkasan'
    | '/api/health'
    | '/riwayat/$orderId'
    | '/sukses/$orderId'
    | '/riwayat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anggota'
    | '/checkout'
    | '/keranjang'
    | '/laporan'
    | '/masuk'
    | '/produk'
    | '/pulihkan'
    | '/ringkasan'
    | '/api/health'
    | '/riwayat/$orderId'
    | '/sukses/$orderId'
    | '/riwayat'
  id:
    | '__root__'
    | '/'
    | '/anggota'
    | '/checkout'
    | '/keranjang'
    | '/laporan'
    | '/masuk'
    | '/produk'
    | '/pulihkan'
    | '/ringkasan'
    | '/api/health'
    | '/riwayat/$orderId'
    | '/sukses/$orderId'
    | '/riwayat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnggotaRoute: typeof AnggotaRoute
  CheckoutRoute: typeof CheckoutRoute
  KeranjangRoute: typeof KeranjangRoute
  LaporanRoute: typeof LaporanRoute
  MasukRoute: typeof MasukRoute
  ProdukRoute: typeof ProdukRoute
  PulihkanRoute: typeof PulihkanRoute
  RingkasanRoute: typeof RingkasanRoute
  ApiHealthRoute: typeof ApiHealthRoute
  RiwayatOrderIdRoute: typeof RiwayatOrderIdRoute
  SuksesOrderIdRoute: typeof SuksesOrderIdRoute
  RiwayatIndexRoute: typeof RiwayatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota': {
      id: '/anggota'
      path: '/anggota'
      fullPath: '/anggota'
      preLoaderRoute: typeof AnggotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk': {
      id: '/produk'
      path: '/produk'
      fullPath: '/produk'
      preLoaderRoute: typeof ProdukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulihkan': {
      id: '/pulihkan'
      path: '/pulihkan'
      fullPath: '/pulihkan'
      preLoaderRoute: typeof PulihkanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ringkasan': {
      id: '/ringkasan'
      path: '/ringkasan'
      fullPath: '/ringkasan'
      preLoaderRoute: typeof RingkasanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riwayat/': {
      id: '/riwayat/'
      path: '/riwayat'
      fullPath: '/riwayat/'
      preLoaderRoute: typeof RiwayatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riwayat/$orderId': {
      id: '/riwayat/$orderId'
      path: '/riwayat/$orderId'
      fullPath: '/riwayat/$orderId'
      preLoaderRoute: typeof RiwayatOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sukses/$orderId': {
      id: '/sukses/$orderId'
      path: '/sukses/$orderId'
      fullPath: '/sukses/$orderId'
      preLoaderRoute: typeof SuksesOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnggotaRoute: AnggotaRoute,
  CheckoutRoute: CheckoutRoute,
  KeranjangRoute: KeranjangRoute,
  LaporanRoute: LaporanRoute,
  MasukRoute: MasukRoute,
  ProdukRoute: ProdukRoute,
  PulihkanRoute: PulihkanRoute,
  RingkasanRoute: RingkasanRoute,
  ApiHealthRoute: ApiHealthRoute,
  RiwayatOrderIdRoute: RiwayatOrderIdRoute,
  SuksesOrderIdRoute: SuksesOrderIdRoute,
  RiwayatIndexRoute: RiwayatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
